<li> <a href="[field:arcurl/]" class="news_list_img bl fl"> <img src="[field:litpic/]">
        <div class="img_round"></div>
        </a> &nbsp;
        <div class="news_list_txt fr">
          <div class="bt"> <a href="[field:arcurl/]">[field:title /]</a> <span class="fgx">/</span><span>[field:pubdate function="GetDateTimeMK(@me)"/]</span></div>
          <div class="con">[field:body function='cn_substr(html2text(@me),500)'/]...</div>
        </div>
      </li>