 
      <div class="plan">
        <div class="plan_img"> <a href="[field:typelink/]"><img src="/images/plan_img[field:global name=autoindex runphp="yes"]@me=@me+1;[/field:global].png"></a> </div>
        <div class="plan_con">
          <div class="plan_con_bt"> <a href="[field:typelink/]">[field:typename /] </a> </div>
          <div class="plan_con_txt"> [field:content function='cn_substr(html2text(@me),150)'/]...... </div>
          <a href="[field:typelink/]" class="more bl">
          <div class="more_txt">MORE</div>
          </a> </div>
      </div>
    