<li style="display:none"> <a href="[field:arcurl/]" class="news_list_img bl fl"> <img src="[field:litpic/]" width="70" height="70"/>
            <div class="img_round"></div>
            </a>
            <div class="news_list_txt fr">
              <div class="bt"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></div>
              <div class="con">[field:body function='cn_substr(html2text(@me),180)'/]...</div>
            </div>
          </li>