<?php
$z[0]=Array("field","",149,171);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",172,198);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",223,252);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",285,343);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",647,682);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",685,723);
$z[5][4]['filename']="tonglan.htm";
$z[6]=Array("field","",783,842);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopTypename(@me)";
$z[7]=Array("channel"," <a href=\"[field:typelink/]\" title=\"[field:typename /]\" >[field:typename /]</a> ",878,1063);
$z[7][4]['type']="sun";
$z[7][4]['currentstyle']="<a href='~typelink~' class='cur'>~typename~</a>";
$z[8]=Array("arclist","\r\n        <div class=\"img\"><img src=\"[field:litpic/]\"  width=\"589\" height=\"421\"/></div>\r\n        <a href=\"[field:arcurl/]\" class=\"bl\">\r\n        <div class=\"case_plate_txt\">[field:title /]</div>\r\n        <div class=\"ico\"></div>\r\n        </a>\r\n        <div class=\"case_new_ico\"></div>\r\n        ",1168,1496);
$z[8][4]['flag']="c";
$z[9]=Array("list","\r\n      <li>\r\n        <div class=\"img\"><img src=\"[field:litpic/]\" width=\"294\" height=\"210\"/></div>\r\n        <a href=\"[field:arcurl/]\" class=\"bl\">\r\n        <div class=\"case_plate_txt\">[field:title /]</div>\r\n        <div class=\"case_plate_ico\"></div>\r\n        </a></li>\r\n      ",1518,1827);
$z[9][4]['pagesize']="8";
$z[10]=Array("pagelist","",1905,1962);
$z[10][4]['listsize']="4";
$z[10][4]['listitem']="pageno pre next";
$z[11]=Array("include","",1984,2021);
$z[11][4]['filename']="footer.htm";

?>