<?php
$z[0]=Array("field","",14,42);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",53,79);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",81,110);
$z[2][4]['name']="typename";
$z[3]=Array("channel","<a href=\"[field:typelink/]\" class=\"[field:global runphp='yes' name=autoindex](@me < 1)?@me=\"no_bg\":@me=\"\";[/field:global] \">[field:typename/]</a>",147,345);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>