<?php
$z[0]=Array("global","",458,479);
$z[0][4]['name']="cfg_qq";
$z[1]=Array("channel","\r\n    | <a href='[field:typelink/]'  class=\"top\">[field:typename/]</a>\r\n    ",702,818);
$z[1][4]['type']="top";
$z[2]=Array("global","",862,888);
$z[2][4]['name']="cfg_banquan";
$z[3]=Array("global","",889,915);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",917,941);
$z[4][4]['name']="cfg_beian";

?>