<?php
$z[0]=Array("global","",459,480);
$z[0][4]['name']="cfg_qq";
$z[1]=Array("channel","\r\n    | <a href='[field:typelink/]'  class=\"top\">[field:typename/]</a>\r\n    ",703,819);
$z[1][4]['type']="top";
$z[2]=Array("global","",863,889);
$z[2][4]['name']="cfg_banquan";
$z[3]=Array("global","",890,916);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",918,942);
$z[4][4]['name']="cfg_beian";

?>