<?php
$z[0]=Array("global","",461,482);
$z[0][4]['name']="cfg_qq";
$z[1]=Array("channel","\r\n    | <a href='[field:typelink/]'  class=\"top\">[field:typename/]</a>\r\n    ",705,821);
$z[1][4]['type']="top";
$z[2]=Array("global","",865,891);
$z[2][4]['name']="cfg_banquan";
$z[3]=Array("global","",892,918);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",920,944);
$z[4][4]['name']="cfg_beian";

?>