<?php
$z[0]=Array("global","",327,354);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("field","(@me==\"\")? @me=\"cur\":@me=\"\";",365,443);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channelartlist","\r\n        <li> <a href=\"{dede:field name='typeurl'/}\" class=\"z {dede:field.currentstyle/}\">{dede:field name='typename'/}</a>   \r\n          <div class=\"nav2\">{dede:channel type='son' noself='yes'}<a href=\"[field:typelink/]\" class=\"[field:global runphp='yes' name=autoindex](@me < 1)?@me=\"no_bg\":@me=\"\";[/field:global] \">[field:typename/]</a>{/dede:channel}</div>\r\n        </li>\r\n      ",469,946);
$z[2][4]['typeid']="1,6,12,19,24,28,29,30";
$z[2][4]['currentstyle']="cur";

?>