<?php
$z[0]=Array("field","",149,171);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",172,198);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",223,252);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",285,343);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",645,680);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",683,721);
$z[5][4]['filename']="tonglan.htm";
$z[6]=Array("field","",781,840);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopTypename(@me)";
$z[7]=Array("channel"," <a href=\"[field:typelink/]\" title=\"[field:typename /]\" >[field:typename /]</a> ",876,1061);
$z[7][4]['type']="sun";
$z[7][4]['currentstyle']="<a href='~typelink~' class='cur'>~typename~</a>";
$z[8]=Array("field","",1092,1113);
$z[8][4]['name']="content";
$z[9]=Array("include","",1129,1166);
$z[9][4]['filename']="footer.htm";

?>